version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: mysql_test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      # NO MYSQL_USER
      # NO MYSQL_PASSWORD
      # NO MYSQL_DATABASE
    ports:
      - "3307:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  db_data: {}
